language: ruby
rvm:
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_script:
  - sleep 10
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
addons:
  postgresql: "9.3"
services:
  - elasticsearch
